// M5-01: 300-voter staging load test (firewall-friendly gradual ramp).
// Run with: node --test test/load.test.js
//
// Simulates a 300-participant event against an in-memory D1 (same harness as
// the rest of the suite). The traffic is emitted as a *gradual ramp* — a small
// concurrent pool with a per-request delay — rather than a thundering herd, so
// it looks like real humans arriving over time and does not trip upstream WAF /
// abuse detection. Every scenario below is deterministic and checks the M5-01
// integrity thresholds:
//
//   - each UID has at most one participation row
//   - aggregation equals the pre-computed expected answer
//   - zero orphan ballots / choices / option references
//   - every non-2xx response is an explainable 4xx (no unexpected 5xx)
//
// The load is generated by a bounded async pool so 300 concurrent in-flight
// requests never exceed a small worker count (keeps the local process calm).
import { test, before } from 'node:test';
import assert from 'node:assert/strict';
import { getWorker, newDb, setupJwks, makeJwt, req, createEnv } from './harness.js';

let worker;

before(async () => {
  await setupJwks();
  worker = await getWorker();
});

// --- helpers ---------------------------------------------------------------

function freshEnv() {
  return createEnv(newDb());
}

// Bounded concurrent pool. Runs `tasks` (async fns) with at most `concurrency`
// in flight at once. This is the "gradual ramp" knob: a small pool + a delay
// keeps the request shape human-like instead of a single burst.
async function runConcurrent(tasks, { concurrency = 8, delayMs = 0 } = {}) {
  const results = new Array(tasks.length);
  let cursor = 0;
  async function worker() {
    while (cursor < tasks.length) {
      const i = cursor++;
      if (delayMs) await sleep(delayMs);
      results[i] = await tasks[i]();
    }
  }
  const pool = [];
  for (let i = 0; i < Math.min(concurrency, tasks.length); i++) pool.push(worker());
  await Promise.all(pool);
  return results;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// A distinct per-voter IP, so the per-IP auth budget (M3-04) does not collide
// across the 300 simulated users the way it would in a shared-IP mock.
function ip(sub) {
  const n = Number(sub.replace(/\D/g, '')) || 0;
  return `203.0.113.${n % 255}`;
}

// Dispatch a vote as a specific voter, tagging the request with that voter's
// distinct IP so the per-IP auth budget does not collapse all mock users onto
// one bucket. `extra` carries optional headers (e.g. Idempotency-Key).
async function vote(env, pollId, sub, { choices, headers = {} } = {}) {
  const voter = await makeJwt(sub, `${sub}@load.test`, 'user');
  return worker.fetch(req(`/api/polls/${pollId}/vote`, {
    method: 'POST',
    token: voter,
    body: { choices },
    headers: { 'x-forwarded-for': ip(sub), ...headers }
  }), env, {});
}

async function openPoll(env, superToken, overrides = {}) {
  const body = {
    title: 'Load Test Poll',
    description: 'A poll for a 300-participant load test.',
    anonymity: 'named',
    voteMode: 'multiple',
    maxVotes: 2,
    allowChange: true,
    options: [
      { id: 'a', code: 'A', label: 'Option A' },
      { id: 'b', code: 'B', label: 'Option B' },
      { id: 'c', code: 'C', label: 'Option C' }
    ],
    status: 'open',
    eligibilityMode: 'public',
    resultsVisibility: 'public',
    ...overrides
  };
  const res = await worker.fetch(req('/api/polls', {
    method: 'POST',
    token: superToken,
    body
  }), env, {});
  const data = await res.json();
  if (res.status !== 201) throw new Error(`createPoll failed: ${res.status} ${JSON.stringify(data)}`);
  return data.id;
}

function jwt(sub, role = 'user') {
  // Super admin is identified by email (isSuper), so pass the real email when
  // the role is admin; every other role just needs a distinct sub.
  if (role === 'admin') return makeJwt('super', 'jamespolik@gmail.com', 'admin');
  return makeJwt(sub, `${sub}@load.test`, role);
}

// Integrity assertions shared by every scenario.
function assertIntegrity(env, pollId, expected) {
  // 1. each UID has at most one participation row.
  const partCount = env.DB.prepare('SELECT COUNT(*) n FROM participation WHERE poll_id=?').bind(pollId).first().n;
  const distinctUids = env.DB.prepare('SELECT COUNT(DISTINCT uid) n FROM participation WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(partCount, distinctUids, `every UID has at most one participation row (${partCount} vs ${distinctUids})`);

  // 2. aggregation equals the pre-computed expected answer.
  const opts = env.DB.prepare('SELECT id FROM options WHERE poll_id=?').bind(pollId).all().results;
  const counts = env.DB.prepare('SELECT option_id, SUM(votes) v FROM ballot_choices WHERE poll_id=? GROUP BY option_id').bind(pollId).all().results;
  const tally = {};
  for (const o of opts) tally[o.id] = 0;
  for (const r of counts) tally[r.option_id] = Number(r.v || 0);
  for (const [k, v] of Object.entries(expected)) assert.equal(tally[k], v, `option ${k} vote count`);

  // 3. zero orphan ballots / choices / option references.
  const orphanChoices = env.DB.prepare(
    'SELECT COUNT(*) n FROM ballot_choices bc LEFT JOIN ballots b ON b.id=bc.ballot_id WHERE bc.poll_id=? AND b.id IS NULL'
  ).bind(pollId).first().n;
  assert.equal(orphanChoices, 0, 'no orphan ballot_choices');
  const orphanOptions = env.DB.prepare(
    'SELECT COUNT(*) n FROM ballot_choices bc LEFT JOIN options o ON o.id=bc.option_id WHERE bc.poll_id=? AND o.id IS NULL'
  ).bind(pollId).first().n;
  assert.equal(orphanOptions, 0, 'no orphan option references');
}

// --- M5-01 scenarios -------------------------------------------------------

test('M5-01-01: 300 voters ramp in, integrity holds', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  const pollId = await openPoll(env, superToken);

  // Expected answer: 300 distinct voters, each selecting exactly option 'a'.
  const expected = { a: 300, b: 0, c: 0 };

  const tasks = [];
  for (let i = 0; i < 300; i++) {
    const sub = `v${i}`;
    tasks.push(async () => {
      const v = await vote(env, pollId, sub, { choices: [{ optionId: 'a', votes: 1 }] });
      assert.ok(v.status === 200, `voter ${sub} got ${v.status}`);
      return v;
    });
  }

  // Gradual ramp: 12 concurrent, ~15 ms spacing. 300 voters in ~3.75 s.
  const results = await runConcurrent(tasks, { concurrency: 12, delayMs: 15 });

  // No unexpected 5xx.
  for (const r of results) assert.ok(r.status < 500, `no unexpected 5xx on ${r.status}`);

  // Integrity gates.
  assertIntegrity(env, pollId, expected);

  const totalParticipants = env.DB.prepare('SELECT COUNT(*) n FROM participation WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(totalParticipants, 300, '300 participants tallied');

  // Results endpoint must also aggregate correctly.
  const admin = await jwt('super', 'admin');
  const res = await worker.fetch(req(`/api/polls/${pollId}/results`, { token: admin }), env, {});
  assert.equal(res.status, 200);
  const data = await res.json();
  assert.equal(data.totalParticipants, 300);
  const a = data.results.find((o) => o.code === 'A');
  assert.equal(a.votes, 300);
});

test('M5-01-02: retries + double-clicks replay via Idempotency-Key (no double-count)', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  const pollId = await openPoll(env, superToken);

  // 200 voters, each fires 3 duplicate POSTs with the SAME idempotency key
  // (simulates double-click + network retry). Each must count once.
  const tasks = [];
  for (let i = 0; i < 200; i++) {
    const sub = `r${i}`;
    const key = crypto.randomUUID();
    tasks.push(async () => {
      for (let attempt = 0; attempt < 3; attempt++) {
        const v = await vote(env, pollId, sub, {
          choices: [{ optionId: 'b', votes: 1 }],
          headers: { 'Idempotency-Key': key }
        });
        assert.ok(v.status === 200, `attempt ${attempt} for ${sub} got ${v.status}`);
      }
    });
  }
  await runConcurrent(tasks, { concurrency: 16, delayMs: 8 });

  // 200 distinct participants, each counted once for option b.
  const partCount = env.DB.prepare('SELECT COUNT(*) n FROM participation WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(partCount, 200, 'no double-count from retries');
  const idemRows = env.DB.prepare('SELECT COUNT(*) n FROM idempotency_keys WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(idemRows, 200, 'one idempotency row per voter');
  assertIntegrity(env, pollId, { a: 0, b: 200, c: 0 });
});

test('M5-01-03: disconnect/reconnect — lost response retried with same key', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  const pollId = await openPoll(env, superToken);

  // Each voter's first POST "loses" its response (we ignore it); the retry with
  // the same key must replay, not double-count.
  const tasks = [];
  for (let i = 0; i < 150; i++) {
    const sub = `d${i}`;
    const key = crypto.randomUUID();
    tasks.push(async () => {
      const first = await vote(env, pollId, sub, {
        choices: [{ optionId: 'c', votes: 1 }],
        headers: { 'Idempotency-Key': key }
      });
      // Simulate lost response: ignore first, retry with same key.
      const retry = await vote(env, pollId, sub, {
        choices: [{ optionId: 'c', votes: 1 }],
        headers: { 'Idempotency-Key': key }
      });
      assert.ok(first.status === 200, `first ${sub} got ${first.status}`);
      const rb = await retry.json();
      assert.equal(rb.ok, true, 'retry replays cached ok');
      assert.equal(rb.changed, false, 'retry does not change the tally');
    });
  }
  await runConcurrent(tasks, { concurrency: 10, delayMs: 10 });

  const partCount = env.DB.prepare('SELECT COUNT(*) n FROM participation WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(partCount, 150, 'lost-response retry does not double-count');
  assertIntegrity(env, pollId, { a: 0, b: 0, c: 150 });
});

test('M5-01-04: change-vote under allowChange updates the tally once per voter', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  const pollId = await openPoll(env, superToken);

  // 120 voters each cast an initial vote, then a second vote selecting a
  // different option. With allowChange=true the tally reflects only the latest.
  const tasks = [];
  for (let i = 0; i < 120; i++) {
    const sub = `c${i}`;
    tasks.push(async () => {
      await vote(env, pollId, sub, { choices: [{ optionId: 'a', votes: 1 }] });
      const v2 = await vote(env, pollId, sub, { choices: [{ optionId: 'b', votes: 1 }] });
      assert.ok(v2.status === 200, `change-vote ${sub} got ${v2.status}`);
    });
  }
  await runConcurrent(tasks, { concurrency: 10, delayMs: 12 });

  // 120 distinct participants, each now on option b (a dropped).
  const partCount = env.DB.prepare('SELECT COUNT(*) n FROM participation WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(partCount, 120, 'change-vote keeps one participation per voter');
  assertIntegrity(env, pollId, { a: 0, b: 120, c: 0 });
});

test('M5-01-05: mass voting at the deadline (all 300 in a tight window)', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  // Poll with an endAt slightly in the future so the deadline path is exercised.
  const endAt = new Date(Date.now() + 60_000).toISOString();
  const pollId = await openPoll(env, superToken, { endAt });

  const expected = { a: 300, b: 0, c: 0 };
  const tasks = [];
  for (let i = 0; i < 300; i++) {
    const sub = `e${i}`;
    tasks.push(async () => {
      const v = await vote(env, pollId, sub, { choices: [{ optionId: 'a', votes: 1 }] });
      assert.ok(v.status === 200, `deadline voter ${sub} got ${v.status}`);
    });
  }
  // Tighter concurrency than the ramp test to stress the deadline window.
  await runConcurrent(tasks, { concurrency: 24, delayMs: 3 });

  assertIntegrity(env, pollId, expected);

  // Close the poll; snapshot must be produced and hash-verified.
  const admin = await jwt('super', 'admin');
  const close = await worker.fetch(req(`/api/polls/${pollId}`, {
    method: 'PATCH', token: admin,
    body: { status: 'closed' }
  }), env, {});
  assert.ok(close.status === 200, `close got ${close.status}`);
  const snap = env.DB.prepare('SELECT * FROM poll_result_snapshots WHERE poll_id=?').bind(pollId).first();
  assert.ok(snap, 'snapshot created on close');
});

test('M5-01-06: whitelist import of 1,000 and 5,000 entries', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  const pollId = await openPoll(env, superToken, { eligibilityMode: 'whitelist' });

  // 1,000 entries.
  const n1 = 1000;
  const entries1 = Array.from({ length: n1 }, (_, i) => ({
    email: `wl${i}@example.com`,
    name: `Whitelisted ${i}`
  }));
  const r1 = await worker.fetch(req(`/api/polls/${pollId}/whitelist`, {
    method: 'POST', token: superToken,
    body: { entries: entries1 }
  }), env, {});
  const d1 = await r1.json();
  assert.equal(r1.status, 200, `whitelist 1k import ok (${r1.status})`);
  assert.equal(d1.count, n1);
  const wlCount1 = env.DB.prepare('SELECT COUNT(*) n FROM whitelist WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(wlCount1, n1, '1,000 whitelist rows');

  // Extend to 5,000 (append 4,000 more).
  const n2 = 5000;
  const entries2 = Array.from({ length: n2 - n1 }, (_, i) => ({
    email: `wl${n1 + i}@example.com`,
    name: `Whitelisted ${n1 + i}`
  }));
  const r2 = await worker.fetch(req(`/api/polls/${pollId}/whitelist`, {
    method: 'POST', token: superToken,
    body: { entries: entries2 }
  }), env, {});
  const d2 = await r2.json();
  assert.equal(r2.status, 200, `whitelist 5k import ok (${r2.status})`);
  assert.equal(d2.count, n2 - n1);
  const wlCount2 = env.DB.prepare('SELECT COUNT(*) n FROM whitelist WHERE poll_id=?').bind(pollId).first().n;
  assert.equal(wlCount2, n2, '5,000 whitelist rows total');

  // A whitelisted voter can actually vote. The whitelist eligibility check
  // matches on user.email, so mint a JWT whose sub/email both match the entry.
  // sign_in_provider must be google.com (real Firebase tokens set it; the worker
  // trusts only Google sign-in tokens at M3-03), so pass 'google.com' here rather
  // than null (which drops the claim and fails auth).
  const voter = await makeJwt('wl5', 'wl5@example.com', 'user', 'Whitelisted 5', 'google.com');
  const v = await worker.fetch(req(`/api/polls/${pollId}/vote`, {
    method: 'POST',
    token: voter,
    body: { choices: [{ optionId: 'a', votes: 1 }] }
  }), env, {});
  assert.equal(v.status, 200, `whitelisted voter ${v.status}`);
});

test('M5-01-07: invalid requests return explainable 4xx, no unexpected 5xx', async () => {
  const env = freshEnv();
  const superToken = await jwt('super', 'admin');
  const pollId = await openPoll(env, superToken);

  const cases = [];

  // malformed body
  cases.push(async () => {
    const r = await worker.fetch(req(`/api/polls/${pollId}/vote`, {
      method: 'POST', token: jwt('x1'), body: { choices: 'not-an-array' }
    }), env, {});
    assert.ok(r.status >= 400 && r.status < 500, `malformed body -> 4xx (${r.status})`);
  });

  // empty choices
  cases.push(async () => {
    const r = await worker.fetch(req(`/api/polls/${pollId}/vote`, {
      method: 'POST', token: jwt('x2'), body: { choices: [] }
    }), env, {});
    assert.ok(r.status >= 400 && r.status < 500, `empty choices -> 4xx (${r.status})`);
  });

  // too many votes
  cases.push(async () => {
    const r = await worker.fetch(req(`/api/polls/${pollId}/vote`, {
      method: 'POST', token: jwt('x3'), body: { choices: [{ optionId: 'a', votes: 5 }] }
    }), env, {});
    assert.ok(r.status >= 400 && r.status < 500, `over-max votes -> 4xx (${r.status})`);
  });

  // unauthorized (bad token)
  cases.push(async () => {
    const bad = await makeJwt('bad', 'bad@example.com', 'user', 'Bad', null);
    const r = await worker.fetch(req(`/api/polls/${pollId}/vote`, {
      method: 'POST', token: bad, body: { choices: [{ optionId: 'a', votes: 1 }] }
    }), env, {});
    assert.ok(r.status === 401 || r.status === 403, `bad token -> 401/403 (${r.status})`);
  });

  await runConcurrent(cases, { concurrency: 4 });
});
